development:
  adapter: postgresql
  encoding: unicode
  database: conectate_carolina_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: conectate_carolina_test
  pool: 5
  timeout: 5000

production:
   adapter: postgresql
   encoding: unicode
   database: conectate_carolina_production
   pool: 5
