# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: a38eb52885d37e92d36b945c7af60bb4995d35f25943a24c6408edb67b4e193d29b519c69e3e72e9c7fdcab0d6b61890fcb1afa485dde35fa23410d27cc711ff

test:
  domain_name: example.com 
  secret_key_base: 2f3e09b62dc2e9a792d2ba66132fe04d1c50515414dfc0a12d3349ce37d131e6a762f3992b721594d294ff7eb459b4e00498ea597d300790ef8148cdb36d70da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
